version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: emmo-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: emmo
      POSTGRES_PASSWORD: emmo
      POSTGRES_DB: emmo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 