import tailwindcssAnimate from 'tailwindcss-animate';
import tailwindcssTypography from '@tailwindcss/typography';

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ['class'],
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    container: {
      center: true,
      padding: '1.5rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      colors: {
        primary: 'var(--primary)',
        'oslo-gray-50': 'var(--oslo-gray-50)',
        'oslo-gray-100': 'var(--oslo-gray-100)',
        'oslo-gray-200': 'var(--oslo-gray-200)',
        'oslo-gray-300': 'var(--oslo-gray-300)',
        'oslo-gray-400': 'var(--oslo-gray-400)',
        'oslo-gray-500': 'var(--oslo-gray-500)',
        'oslo-gray-600': 'var(--oslo-gray-600)',
        'oslo-gray-700': 'var(--oslo-gray-700)',
        'oslo-gray-800': 'var(--oslo-gray-800)',
        'oslo-gray-900': 'var(--oslo-gray-900)',
        'oslo-gray-950': 'var(--oslo-gray-950)',
        'grey-50': 'var(--grey-50)',
        'grey-100': 'var(--grey-100)',
        'grey-200': 'var(--grey-200)',
        'grey-300': 'var(--grey-300)',
        'grey-400': 'var(--grey-400)',
        'grey-500': 'var(--grey-500)',
        'grey-600': 'var(--grey-600)',
        'grey-700': 'var(--grey-700)',
        'grey-800': 'var(--grey-800)',
        'grey-900': 'var(--grey-900)',
        white: 'var(--base-white)',
        black: 'var(--base-black)',
        warning: 'var(--base-warning)',
        success: 'var(--base-success)',
        blue: 'var(--blue)',
        violet: 'var(--violet)',
        fuchsia: 'var(--fuchsia)',
        pink: 'var(--pink)',
        red: 'var(--red)',
        orange: 'var(--orange)',
        'gradient-01': 'var(--gradient-01)',
        'gradient-02': 'var(--gradient-02)',
        'gradient-03': 'var(--gradient-03)',
        'radio-default': 'var(--radio-default)',
        'red-50': 'var(--red-50)',
        'red-100': 'var(--red-100)',
        'red-200': 'var(--red-200)',
        'red-300': 'var(--red-300)',
        'red-500': 'var(--red-500)',
        'red-600': 'var(--red-600)',
        'red-700': 'var(--red-700)',
        'red-800': 'var(--red-800)',
        'red-900': 'var(--red-900)',
        'yellow-50': 'var(--yellow-50)',
        'yellow-100': 'var(--yellow-100)',
        'yellow-200': 'var(--yellow-200)',
        'yellow-700': 'var(--yellow-700)',
        'brown-100': 'var(--brown-100)',
        'brown-300': 'var(--brown-300)',
        'brown-500': 'var(--brown-500)',
        'brown-600': 'var(--brown-600)',
        'brown-700': 'var(--brown-700)',
        'brown-900': 'var(--brown-900)',
      },
      fontSize: {
        'display-lg': ['57px', { lineHeight: '64px', letterSpacing: '-0.25px' }],
        'display-md': ['45px', { lineHeight: '52px' }],
        'display-sm': ['36px', { lineHeight: '44px' }],
        'headline-lg': ['32px', { lineHeight: '40px' }],
        'headline-md': ['28px', { lineHeight: '36px' }],
        'headline-sm': ['24px', { lineHeight: '32px' }],
        'headline-xs': ['20px', { lineHeight: '32px' }],
        'title-lg': ['22px', { lineHeight: '28px' }],
        'title-md': ['16px', { lineHeight: '24px', letterSpacing: '+0.15px' }],
        'title-sm': ['14px', { lineHeight: '20px', letterSpacing: '+0.1px' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '+0.1px' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '+0.5px' }],
        'label-sm': ['11px', { lineHeight: '16px', letterSpacing: '+0.5px' }],
        'body-xl': ['20px', { lineHeight: '24px', letterSpacing: '+0.5px' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '+0.5px' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '+0.25px' }],
        'body-sm': ['12px', { lineHeight: '16px', letterSpacing: '+0.4px' }],
        'body-xs': ['10px', { lineHeight: '16px', letterSpacing: '+0.4px' }],
      },
      screens: {
        xs: '390px',
      },
      maxWidth: {
        100: '400px',
        200: '800px',
        300: '1200px',
      },
      spacing: {
        15: '60px',
        30: '120px',
      },
    },
  },
  plugins: [tailwindcssAnimate, tailwindcssTypography],
};
